server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/softlog_db2
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

security.oauth2.client:
  client-id: squad1
  client-secret: 123
  scope: password
  
jwt:
  privateKey: -----BEGIN PRIVATE KEY-----MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQD75xF5LQ8tenLrY778VNXduPvYhfbryH0UjoiewXX/5GBr9FKPkqkpxCLbVIu6+w8CyJliZpmMoEl03Lr2BiZvjEUQvdfx3KuPlxKRWm0dsy8Od6G7wFbLl/kTx6F4n8Eg7LKyvJNz14EpvGG/AY7dAd1nTX5irjW0Iu/iK18/UDY6aQCmIGhNgE0yX9RI0UAQ9xcoUF88mba+UPdGaK1yugL3/eSO/vBZm3kqUm7ZQL3FOQvsMCPGaH9W1BCgtroeLcG+sPitlYuWesDxQQYo8DoRU/mNNALKXxzzAeuRPuZoV6/mJGOtAerTatWf/+BV7owquSLNQ4Gk+YP1kH+tAgMBAAECggEAbBZ9N+quvYvyLbDSLYHVdts+LW1mQ0v259A1LTHECTYcbZYbqwF6VrKTZluDzYqWqVIcBs4RivboLh3cl16SNYERzZo4Q861Stq/G+GaOok9Ys7QdjiUxa2DMgqR7alW/GK0Vt91wdox0Q/FPWlUvN5k+0OUPJGV96KaHgkQSKCvhKotictyBUF2WO/WdM9NrzvX8QdW7fI+6BlTxFKiU11bh5f1k8YvORJOFaN9EOaa5KOWvHlvNckzdUihxvgacYsx3Y6yDVIws5rc8IEhz24y9kEnaoi0YF5E6BGbXrgBM/ULH17TVaTSxESVKwxwxTaTQFp98jNm+9rL4f1iXQKBgQD/vgqv1I7wmNehBzItSxQBHJeoDBMyntxBbraYrydnlS77eldzzBbgA2Hj1gpt2jC9NM3LZCP1JLKZTv1Lp3jEHCnYXLD4gJO5ZlHpLuyFnHwaJDj3HfHDXJJH0P2ztpzCEiTCH+duqdDF1RSm5SpqfpWlKCfE5lhQHDclcoOM1wKBgQD8KAlEz7PAzPFSfH0/+EnWDMPxwYwTKP62rh9o1eIuRzg3LOzBJdh/MCGKHTx2nDgyNBGIk3rklOhByicW1gfdNo4Sbs21Elc4jxz52TKNYSXpru1sDnNtAB11u+p12JTn+L1wJrMPR+wN3qc6KHiWf6i3wRtWRFhOeybIiuLjGwKBgDBbVtn4by6/N8aS/cHiuF2dcm+sGNUxhKQ6svwb4m+Lnd6fO3oB1TF2ckQKbN5oq16bZW5X+RSZY8vpS6vKduNeD+uBW1Uhus0Ls+FLph19gVnQD5VqbBRspJw/wDkDBpELrTenoLMkGP3PVKBaJLMOTG12Mk7g30IGk8bY6FbxAoGAZ7Tnqv9pxKAFmJFOyiKJ65kwdZvOyoqPx/5xOKLO9Y2hF0BI11+DXTwkbzN7DKVPj4ZOt8dAQgbkRzqnPQMmFNs9L2OXAyPZ748csb2cxvzvpN6nE0wWOPxVIXj6AyHijE2HTDr+ZgiEk2fBi2/duLgkYf7wCVjuoMiRuOU2T4UCgYBR8SRRwZ41sSzH+uJlBNqrR7MTM8BA99FlPSFxegbRa9IHM2GMiT6tuqANxx4+43jFUhVsN9DcaIcTHS4GYJVIz4MH+sPt8zYveelnRx1xnhYQSTykPNR5p1uVODaXkU6Pp/6H8DNc4BgwsiYi0EwpQCTDVl10fO7CDQjSaeMi0g==-----END PRIVATE KEY-----
  publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA++cReS0PLXpy62O+/FTV3bj72IX268h9FI6InsF1/+Rga/RSj5KpKcQi21SLuvsPAsiZYmaZjKBJdNy69gYmb4xFEL3X8dyrj5cSkVptHbMvDnehu8BWy5f5E8eheJ/BIOyysryTc9eBKbxhvwGO3QHdZ01+Yq41tCLv4itfP1A2OmkApiBoTYBNMl/USNFAEPcXKFBfPJm2vlD3RmitcroC9/3kjv7wWZt5KlJu2UC9xTkL7DAjxmh/VtQQoLa6Hi3BvrD4rZWLlnrA8UEGKPA6EVP5jTQCyl8c8wHrkT7maFev5iRjrQHq02rVn//gVe6MKrkizUOBpPmD9ZB/rQIDAQAB-----END PUBLIC KEY-----
  expiration: 86400000
  